# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # SharedKernel Services
    App\SharedKernel\:
        resource: '../src/SharedKernel/'
        exclude:
            - '../src/SharedKernel/Domain/ValueObject/'
            - '../src/SharedKernel/Domain/Event/'
            - '../src/SharedKernel/Domain/Exception/'

    # API Context Services
    App\Api\:
        resource: '../src/Api/'
        exclude:
            - '../src/Api/Domain/*/Entity/'
            - '../src/Api/Domain/*/ValueObject/'
            - '../src/Api/Domain/*/Event/'
            - '../src/Api/Application/*/DTO/'

    # Admin Context Services
    App\Admin\:
        resource: '../src/Admin/'
        exclude:
            - '../src/Admin/Domain/*/Entity/'
            - '../src/Admin/Domain/*/ValueObject/'
            - '../src/Admin/Application/*/DTO/'

    # Web Context Services
    App\Web\:
        resource: '../src/Web/'
        exclude:
            - '../src/Web/Domain/*/Entity/'
            - '../src/Web/Domain/*/ValueObject/'

    # Repository Interfaces Binding
    App\Api\Domain\Post\Repository\PostRepositoryInterface:
        alias: App\Api\Infrastructure\Persistence\Doctrine\Repository\DoctrinePostRepository

    App\Api\Domain\User\Repository\UserRepositoryInterface:
        alias: App\Api\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository
